# Dockerfile.etl
FROM python:3.11-slim

# Install GDAL CLI (ogr2ogr) and its C libs
RUN apt-get update && apt-get install -y \
      gdal-bin \
      libgdal-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt python-dotenv psycopg2-binary

COPY init_db.py .env ./

ENTRYPOINT ["python3", "init_db.py"]